spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huaqianshu/backend-system
          searchPaths: respo
          username:
          password:
        default-label: master
