spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huaqianshu/backend-system
          username:
          password:
          search-paths: respo
        default-label: master
