
spring:
  datasource:
    username: anycall30
    password: anycalluat
    url: jdbc:mysql://139.196.209.200:53306/anycall30?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    filters: statN
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    #初始化连接大小
#    initialSize: 7
#    #连接池最小空闲
#    minIdle: 5
#    #连接池最大使用连接数量
#    maxActive: 20
#    #获取连接最大等待时间
#    maxWait: 60000
#    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    #配置一个连接在池中最小生存的时间，单位是毫秒
#    minEvictableIdleTimeMillis: 300000
#    maxPoolPreparedStatementPerConnectionSize: 20


#logging.file: demo.log
intelligencework:
  #post-url: http://139.196.209.200:8080
  post-url: http://192.168.2.11:9000
#  post-url: http://139.196.209.200:8080
  token: 14F4FEA7-CE81-4277-94F1-A8FC74CB01E0
