
#logging.level.root: INFO
#logging.level.org.springframework.web: DEBUG
#logging.level.org.hibernate: ERROR
#logging.path: /home/admin/application/logs
##logging.file: demo.log
spring:
  profiles:
    # 这里的意思是启用dev环境
    active: dev

#---
#spring:
#  profiles: dev